### ISSUE TITLE
Port of official tf release?

### ISSUE THREAD

**Issue by bluesky314** [romulus0914/EfficientDet-PyTorch#1]
There are many pytorch implementations that came prior to the official tf release that had some discrepancies with the true architecture. A common one was the people used regular convolution in the bipyramidal fpn layers when it was actually mobilenetv2 blocks. I see you use the mobilenet blocks. Is this a port of the official release?

**Comment by bluesky314** [comment]
Also is the port complete or are there still any parts left?

**Comment by romulus0914** [comment]
Hi, thanks for your interest in my repo. However, this is not the official implementation of EfficientDet, and I am simply based on the official one and implement it in PyTorch. There are indeed some situations like you mentioned that some other PyTorch implementations have some difference with the official one. In addition to the "depthwise separable convolutions", I recognize that the official implementation utilizes  "maxpool/nearest upsampling + 1x1 convolutions" to downsample/upsample the features to desirable widths and channels instead of stride 2 convolutions which are employed in some PyTorch implementations.

Further questions are welcomed.

**Comment by bluesky314** [comment]
Thanks for quick reply. I just wanted to know if it has been ported from the official release. Are there any differences from the official you know of from your implementation? Did you try running and seeing if you get similar validation scores?

**Comment by romulus0914** [comment]
As far as I know, there is no difference between the official implementation and mine. However, I do not have time to run the object detection training. Sorry for the inconvenience.

**Comment by bluesky314** [comment]
I have posted questions as separate issues
